// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBDgBWNLXyQpuUx2WPUp4Rzko0cFbiUlXc',
    appId: '1:374371154295:web:b5a88836484c9992a6c972',
    messagingSenderId: '374371154295',
    projectId: 'f-01man-com',
    authDomain: 'f-01man-com.firebaseapp.com',
    storageBucket: 'f-01man-com.appspot.com',
    measurementId: 'G-RY72W9MWB6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBQzvf3rQyjmp7zNRaHxJbcuzEMdHsLpnw',
    appId: '1:374371154295:android:512890d29c513ec7a6c972',
    messagingSenderId: '374371154295',
    projectId: 'f-01man-com',
    storageBucket: 'f-01man-com.appspot.com',
  );
}
